theme: jekyll-theme-minimal
title: Pensamento Computacional
description: Atividades didáticas e recursos para a disciplina de Pensamento Computacional
show_downloads: true
github_repo: Kadidjah/Disciplina_PensamentoComputacional
